### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by PsmIndia** [mageplaza/magento-2-google-xml-sitemap#10]
Fatal error:  Class 'Mageplaza\Seo\Helper\Data' not found in /data/web/magento2_staging/app/code/Mageplaza/Sitemap/Helper/Data.php on line 30

**Comment by toandt98** [comment]
Hello,

You have used our latest Core module. Please try downloading and installing it here:

- https://github.com/mageplaza/module-core

Hopefully it will work again.
