### ISSUE TITLE
Message error - One or more Mageplaza extensions are not validated. Click here to validate them.

### ISSUE THREAD

**Issue by lindomarcb** [mageplaza/magento-2-google-xml-sitemap#11]
After install the message "One or more Mageplaza extensions are not validated. Click here to validate them." begin show in administration area,
I disabled the module sitemap mageplaza but the message don't disappear.

Do you help me?

Thanks!

**Comment by Tuvpt** [comment]
You can activate our free modules in the configuration section at the backend page

**Comment by lindomarcb** [comment]
Can you explain the step-by-step instructions on how to activate the module in my store?
I didn't find a solution.

Thank you very much
