### ISSUE TITLE
HTML Sitemap does not filter by store

### ISSUE THREAD

**Issue by daaannorris** [mageplaza/magento-2-google-xml-sitemap#13]
When in multistore mode the HTML sitemap does not filter the page collection by the current store, resulting in the pages from other stores rendering in the sitemap thus 404s.

Short term I was able to add a preference to add the below filter which resolved the issue:

```    
    /**
     * @inheritDoc
     */
    public function getPageCollection()
    {
        return $this->pageCollection->addFieldToFilter('is_active', Page::STATUS_ENABLED)
            ->addStoreFilter($this->_storeManager->getStore())
            ->addFieldToFilter('identifier', [
                'nin' => $this->getExcludedPages()
            ]);
    }
```

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
We will apply your patch in the next update.
Thank you for your contribution.
It's a pleasure to have a wonderful customer like you.

**Comment by giaphn** [comment]
Closed due no response within 7 days.
