### ISSUE TITLE
HTML sitemap  404 error: Page not found

### ISSUE THREAD

**Issue by ilias159** [mageplaza/magento-2-google-xml-sitemap#16]
Magento ver. 2.3.6-p1
Html sitemap enabled and return 404 error
https://magento-store.com/sitemap/  return 404 error: Page not found 
Note: Multi-store view Enabled (subdomain for international)

Please help me to resolve this problem ??

**Comment by phutx** [comment]
Hi @ilias159,

I can not reproduce your issue locally. Please submit a ticket to get better support.
You can contact us here: https://www.mageplaza.com/contact.html

Thanks!
