### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mp_exclude_sitemap' cannot be null

### ISSUE THREAD

**Issue by dehaanmedia** [mageplaza/magento-2-google-xml-sitemap#3]
When I install Mageplaza sitemap and seo module and run bin/magento setup:upgrade, then I get this error. 

Upgrading data... SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mp_exclude_sitemap' cannot be null, query was: INSERT INTO `cms_page` (`page_id`, `title`, `page_layout`, `meta_keywords`, `meta_description`, `identifier`, `content_heading`, `content`, `is_active`, `layout_update_xml`, `custom_theme`, `custom_root_template`, `custom_layout_update_xml`, `custom_theme_from`, `custom_theme_to`, `meta_title`, `mp_exclude_sitemap`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
[dehaanwebshop@hosting207 staging_html]$ mp_exclude_sitemap' cannot be null

**Comment by peapple** [comment]
I have the same issue. was there any outcome from this?

**Comment by Rjgoolsby** [comment]
Bump. Same here

**Comment by peapple** [comment]
OK. Mageplaza is bit of nightmare. so after month of digging.

Here is the Solution:

Go to your magento database. find a table called cms_page

check a field called: mp_exclude_sitemap

simply delete this field.

I though when I remove magaplaza module  I could just delete the field with mageplaza prefix from database. little did I know here is one with mp_ prefix. that's not cool.
