### ISSUE TITLE
Can't access stores->settings->configuration after install on magento 2.3

### ISSUE THREAD

**Issue by mesnitu** [mageplaza/magento-2-google-xml-sitemap#4]
Hi
I've installed according to the instructions on a magento 2.3
Can't access stores->settings->configuration: 

> [2019-06-18 17:18:06] main.ERROR: Notice: Undefined index: id in magento23.local\vendor\magento\module-config\Model\Config\Structure\Element\Iterator.php on line 63 [] []

Is this working on 2.3?

**Comment by mesnitu** [comment]
checking the modules... do I need to enable Mageplaza_Core ?

**Comment by mesnitu** [comment]
It looks like yes, but now I get One or more Mageplaza extensions are not validated. but can't validate.

**Comment by bdtrung** [comment]
Regarding the activate problem, please follow this solution: https://github.com/mageplaza/module-core/issues/26
