### ISSUE TITLE
Category and product sitemap exclusion defaults to 'yes'

### ISSUE THREAD

**Issue by OvalMedia** [mageplaza/magento-2-google-xml-sitemap#5]
### Preconditions
1. Magento: 2.2.8
2. PHP: 7.1

### Steps to reproduce

1. Install module

### Expected result

1. Category sitemap exclusion should default to 'no'
2. Product sitemap exclusion should default to 'no'

### Actual result

1. Category sitemap exclusion defaults to 'yes'
2. Product sitemap exclusion defaults to 'yes'

The new EAV attribute mp_exclude_sitemap for categories is added to the eav table but the default value for categories and products is 'yes'. I consider this potentiallly fatal as this would mean those categories would be excluded from the sitemap creation. I know the value is not initially saved to the database but all you need to do is open a category for editing (do something else) and then save it. If you don't pay attention the category ends up being exluded.

The default should be 'no' as this is most likely the more common scenario.

Digging deeper I found this: the product attribute seems to be set to default to "no" according to the backend configuration. But this has no effect. You can see that clearly by creating a new product for instance. Sitemap exclusion is set to "yes".

What I don't understand is why you created the product and the category attribute completely different. The product attribute is a global varchar while the category attribute is an integer with a scope for the store level.

**Comment by DrakeJack** [comment]
I'm Drake and I'll assist you in this issue.
We have set the Category and Product exclude sitemap to "Yes" to prevent the sitemap to add product or category unexpected.
If you want to change from "Yes" to "No" by default, here are the file to fix:
 + File app/code/Mageplaza/SiteMap/view/adminhtml/ui_component/category_form.xml
or vendor/mageplaza/magento-2-google-xml-sitemap/view/adminhtml/ui_component/category_form.xml (if you install by composer)
 + And for the product, you should access same directory and in file cms_page_form.xml

Then add this line inside the item name="config" tag
  `<item name="default" xsi:type="string">No</item>`
One more step, you should go to Admin->Store->Atrributes->Products->find mp_exclude_sitemap and change Value Required to "Yes" in the Attribute Properties.

**Comment by Yonn-Trimoreau** [comment]
I'm wondering why any product or any category would be "unexpected"... If it's more the exception than the usual case, then the default value should be "Yes". Otherwise, as @OvalMedia said, your module is really a huge SEO killer...

**Comment by TheFrakes** [comment]
I agree to what Yonn and OvalMedia set. I installed the module and for days I have been trying to find out why no products or categories show up in my sitemap.
I have now learned that on every product page, the switch is set to "yes". Totally strange behaviour and not useful in any way!

**Comment by Yonn-Trimoreau** [comment]
Who's willing to make a PR?

**Comment by valuead** [comment]
@DrakeJack Apparently I have not installed with the composer 
Can you please update your instructions for alternative 
This is a critical issue ... Thank You

**Comment by Yonn-Trimoreau** [comment]
@valuead, fix it yourself, they're not going to fix it soon. Maybe if you buy the premium support they will?

**Comment by taskula** [comment]
The current default behavior is wrong and adds more problems than it is supposed to prevent.

**Comment by OvalMedia** [comment]
Still not fixed.

**Comment by OvalMedia** [comment]
Quick manual fix: go to table eav_attribute and set the field "default_value" to '0' where the "attribute_code" is 'mp_exclude_sitemap'.
Note to dev: change the default value in InstallData from '' (= NULL) to 0.

**Comment by Yonn-Trimoreau** [comment]
Is this issue really completed?
