### ISSUE TITLE
Add option to include OOS product to XML Sitemap

### ISSUE THREAD

**Issue by urosevic** [mageplaza/magento-2-google-xml-sitemap#7]
By default XML Sitemap generated by Mageplaza XML Sitemap does not include Out-of-Stock products.

It would be good to add option to also include OOS products to XML Sitemap as often those products are shown in Catalog with option to customer subscribe and get notification when product back in stock.

Thanks,
Aleksandar

**Comment by bdtrung** [comment]
Hi Aleksandar,
Regarding your problem, you can do quickly customize by removing the "if" condition at line 401 of this file path: Mageplaza/Sitemap/Model/Sitemap.php (http://prntscr.com/prctlk).

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
